name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Restore packages
        run: yarn

      - name: Compile, lint and test
        run: xvfb-run -a yarn run test
        if: runner.os == 'Linux'

      - name: Compile, lint and test
        run: yarn run test
        if: runner.os != 'Linux'
