name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Restore packages
        run: yarn

      - name: Compile, lint and test (Linux)
        run: xvfb-run -a yarn run test
        if: runner.os == 'Linux'

      - name: Compile, lint and test (Windows, Mac)
        run: yarn run test
        if: runner.os != 'Linux'
