name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '47 11 * * SUN'

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        vscode-version: [stable, insiders]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Restore packages
        run: yarn

      - name: Compile, lint and test
        run: yarn run test --label ${{ matrix.vscode-version }}
