name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Restore packages
        run: yarn

      - name: Start xvfb (Linux)
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo ">>> Started xvfb"
        if: success() && runner.os == 'Linux'

      - name: Compile, lint and test
        run: yarn run test
        env:
          DISPLAY: ':99.0'
